### ISSUE TITLE
请问能否集类似vuep的功能

### ISSUE THREAD

**Issue by Mr111222** [chenjiahan/fast-vue-md-loader#1]
![workspace](https://user-images.githubusercontent.com/23070808/51720686-97267880-2089-11e9-91bd-ffc3c55b7062.jpg)

**Comment by Mr111222** [comment]
请问如何去实现这个loader，我要把编辑器加到里面，现在是我加到vueComponent里面了

![image](https://user-images.githubusercontent.com/23070808/51720806-0f8d3980-208a-11e9-8b32-c21218a27c62.png)
![build](https://user-images.githubusercontent.com/23070808/51720833-2f246200-208a-11e9-83ce-e0274ef7779d.jpg)

**Comment by Mr111222** [comment]
![build](https://user-images.githubusercontent.com/23070808/51720869-554a0200-208a-11e9-9578-8410e619d20e.jpg)

**Comment by chenjiahan** [comment]
没有计划支持喔
