### ISSUE TITLE
是否可以增加下对 makdown meta 的支持

### ISSUE THREAD

**Issue by ystarlongzi** [chenjiahan/fast-vue-md-loader#3]
目前项目里也用到本插件转换 md 文档，但是现在有个需求，希望允许在 md 文档最顶部添加一些额外的描述数据，如下：

``` markdown
---
order: 0,
title:
  zh-CN: 按钮
  en-US: Button
---
```

然后使用 [front-matter](https://github.com/jxson/front-matter) 转换成对应的内容后，作为 `wrapper` 方法的第二个参数暴露出去，方便构建的时候使用

但该功能目前对 vant 是非必须的，只是自己项目里会需要用到这样的特性，所以才提出来 😁😁

如果能够接受的话，我可以提个 pr

**Comment by chenjiahan** [comment]
可以的，欢迎 PR

**Comment by chenjiahan** [comment]
已发布，`@vant/markdown-loader@2.2.0`
